### ISSUE TITLE
java.lang.IllegalStateException: Doesn't have any subscription

### ISSUE THREAD

**Issue by klwoon** [lukaspili/Android-Reactive-Billing#3]
On my fragment's `onCreate()` I subscribe to the `purchaseFlow()` as:

``` java
    mSubscription = ReactiveBilling.getInstance(mActivity).purchaseFlow()...
```

And on the fragment's `onDestroy()` I unsubscribe it as:

``` java
    if (mSubscription != null) {
           mSubscription.unsubscribe();
           mSubscription = null;
    }
```

This fragment is triggered by a menu button (and dismissed by another close button within the fragment). When the menu and close button is tapped in quick succession, sometimes I will get the crash as below. May I ask if there's any way to prevent it?

```
                                                            Caused by: java.lang.IllegalStateException: Doesn't have any subscription
                                                               at com.github.lukaspili.reactivebilling.PurchaseFlowService$1.call(PurchaseFlowService.java:38)
                                                               at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                                                               at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                               at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                               at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                               at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                               at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                               at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                               at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                               at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                               at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                               at com.example.controller.MenuMainFragment.onDestroy(MenuMainFragment.java:332)
                                                               at android.support.v4.app.Fragment.performDestroy(Fragment.java:2202)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1196)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                               at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2083)
                                                               at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:244)
                                                               at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:368)
                                                               at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:203)
                                                               at com.example.BaseActivity.onDestroy(BaseActivity.java:131)
                                                               at android.app.Activity.performDestroy(Activity.java:6169)
                                                               at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
                                                               at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
                                                               at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724) 
                                                               at android.app.ActivityThread.access$1400(ActivityThread.java:151) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:135) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by klwoon** [comment]
Not sure if the logcat below is relevant. In `purchaseFlow()` I am subscribing to a Subscriber, and got these `onError`.

``` java
                .subscribe(new Subscriber<PurchaseResponse>() {
                    @Override
                    public void onCompleted() {
                    }

                    @Override
                    public void onError(Throwable e) {
                        Timber.e(e, e.getMessage());
                    }

                    @Override
                    public void onNext(PurchaseResponse response) {
                    }
```

```
                                                            Caused by: rx.exceptions.OnErrorNotImplementedException: Already has subscription
                                                               at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
                                                               at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
                                                               at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                               at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                               at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:810)
                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:571)
                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
                                                               at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
                                                               at rx.observers.Subscribers$5.onError(Subscribers.java:224)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:62)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                               at rx.Observable.subscribe(Observable.java:8553)
                                                               at rx.Observable.subscribe(Observable.java:8520)
                                                               at rx.Observable.subscribe(Observable.java:8343)
                                                               at com.example.controller.MenuMainFragment.onCreate(MenuMainFragment.java:86)
                                                               at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
                                                               at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:779)
                                                               at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:819)
                                                               at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:660)
                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                               at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                               at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
                                                               at com.example.BaseActivity.onStart(BaseActivity.java:72)
                                                               at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                               at android.app.Activity.performStart(Activity.java:6006)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418) 
                                                               at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:135) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5289) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
                                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115) 
                                                            Caused by: java.lang.IllegalStateException: Already has subscription
                                                            at com.github.lukaspili.reactivebilling.PurchaseFlowService$2.call(PurchaseFlowSer
```

**Comment by mruijzendaal** [comment]
Having the exact same log with a 100% reproduction rate.

**Comment by virusman** [comment]
Same here.

**Comment by csabatini** [comment]
Did anyone every achieve a fix or work around for this issue? Or find an alternate RxBilling solution?

This issue alone has introduced so many crashes to my app. But the simplicity of this library is great
